# Generated by Django 4.2.8 on 2024-02-27 10:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("w_app", "0004_garbageb"),
    ]

    operations = [
        migrations.CreateModel(
            name="Complaints",
            fields=[
                ("S_id", models.IntegerField(primary_key=True, serialize=False)),
                ("c_name", models.CharField(max_length=255)),
                ("c_email", models.CharField(max_length=255)),
                ("complaint", models.CharField(max_length=400)),
                ("status", models.CharField(default="-", max_length=255)),
            ],
        ),
    ]
