version: '3.8'
services:
  django_app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/django
    ports:
      - "8000:8000"
    image: app:django
    container_name: my_first_django_container
    command: python manage.py runserver 0.0.0.0:8000
