# Generated by Django 4.2.8 on 2024-02-20 06:25

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Driver",
            fields=[
                ("S_id", models.IntegerField(primary_key=True, serialize=False)),
                ("drv_name", models.CharField(max_length=255)),
                ("drv_phn", models.CharField(max_length=255)),
                ("drv_email", models.CharField(max_length=255)),
                ("drv_place", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="user_d",
            fields=[
                ("S_id", models.IntegerField(primary_key=True, serialize=False)),
                ("Name", models.CharField(max_length=255)),
                ("Email", models.CharField(max_length=255)),
                ("Password", models.CharField(max_length=255)),
            ],
        ),
    ]
