# Generated by Django 4.2.8 on 2024-02-22 09:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("w_app", "0002_driver_drv_psw"),
    ]

    operations = [
        migrations.AddField(
            model_name="user_d",
            name="Address",
            field=models.CharField(default="-", max_length=255),
        ),
        migrations.AddField(
            model_name="user_d",
            name="PhoneNo",
            field=models.CharField(default="-", max_length=255),
        ),
    ]
