# Generated by Django 4.2.8 on 2024-02-27 09:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("w_app", "0003_user_d_address_user_d_phoneno"),
    ]

    operations = [
        migrations.CreateModel(
            name="GarbageB",
            fields=[
                ("S_id", models.IntegerField(primary_key=True, serialize=False)),
                ("g_id", models.CharField(max_length=255)),
                ("g_lat", models.CharField(max_length=255)),
                ("g_lng", models.CharField(max_length=255)),
                ("g_fill", models.CharField(default="-", max_length=255)),
                ("g_status", models.CharField(default="-", max_length=255)),
                ("g_place", models.CharField(max_length=255)),
                ("g_drv", models.CharField(default="-", max_length=255)),
            ],
        ),
    ]
